-- Update content for 'Ball of Fat' (Chunk 27/33)
BEGIN;
-- Append next chunk
UPDATE stories SET original_text = original_text || 'ough the fibres and sap of female trees and produce beings with roots,
      growing from a germ, just as we do, mortal like ourselves, and who will be
      replaced by other beings of the same order, like ourselves again!”

And, standing in front of the brilliant cytisus, whose live pollen was
      shaken off by each breath of air, the senator added:

“Ah, old fellow, if you had to keep count of all your children you
      would be mightily embarrassed. Here is one who generates freely, and then
      lets them go without a pang and troubles himself no more about them.”

“Yes, I do not deny it; we let them go sometimes,” resumed the
      senator, “but we are aware that we do, and that constitutes our
      superiority.”

“No, that is not what I mean,” said the other, shaking his
      head. “You see, my friend, that there is scarcely a man who has not
      some children that he does not know, children—''father unknown''—whom
      he has generated almost unconsciously, just as this tree reproduces.

“If we had to keep account of our amours, we should be just as
      embarrassed as this cytisus which you apostrophized would be in counting
      up his descendants, should we not?

“From eighteen to forty years, in fact, counting in every chance
      cursory acquaintanceship, we may well say that we have been intimate with
      two or three hundred women.

“Well, then, my friend, among this number can you be sure that you
      have not had children by at least one of them, and that you have not in
      the streets, or in the bagnio, some blackguard of a son who steals from
      and murders decent people, i.e., ourselves; or else a daughter in some
      disreputable place, or, if she has the good fortune to be deserted by her
      mother, as cook in some family?

“Consider, also, that almost all those whom we call ''prostitutes''
      have one or two children of whose paternal parentage they are ignorant,
      generated by chance at the price of ten or twenty francs. In every
      business there is profit and loss. These wildings constitute the ''loss'' in
      their profession. Who generated them? You—I—we all did, the
      men called ''gentlemen''! They are the consequences of our jovial little
      dinners, of our gay evenings, of those hours when our comfortable physical
      being impels us to chance liaisons.

“Thieves, marauders, all these wretches, in fact, are our children.
      And that is better for us than if we were their children, for those
      scoundrels generate also!

“I have in my mind a very horrible story that I will relate to you.
      It has caused me incessant remorse, and, further than that, a continual
      doubt, a disquieting uncertainty, that, at times, torments me frightfully.

“When I was twenty-five I undertook a walking tour through Brittany
      with one of my friends, now a member of the cabinet.

“After walking steadily for fifteen or twenty days and visiting the
      Cotes-du-Nord and part of Finistere we reached Douarnenez. From there we
      went without halting to the wild promontory of Raz by the bay of Les
      Trepaases, and passed the night in a village whose name ends in ''of.'' The
      next morning a strange lassitude kept my friend in bed; I say bed from
      habit, for our couch consisted simply of two bundles of straw.

“It would never do to be ill in this place. So I made him get up,
      and we reached Andierne about four or five o''clock in the evening.

“The following day he felt a little better, and we set out again.
      But on the road he was seized with intolerable pain, and we could scarcely
      get as far as Pont Labbe.

“Here, at least, there was an inn. My friend went to bed, and the
      doctor, who had been sent for from Quimper, announced that he had a high
      fever, without being able to determine its nature.

“Do you know Pont Labbe? No? Well, then, it is the most Breton of
      all this Breton Brittany, which extends from the promontory of Raz to the
      Morbihan, of this land which contains the essence of the Breton manners,
      legends and customs. Even to-day this corner of the country has scarcely
      changed. I say ''even to-day,'' for I now go there every year, alas!

“An old chateau laves the walls of its towers in a great melancholy
      pond, melancholy and frequented by flights of wild birds. It has an outlet
      in a river on which boats can navigate as far as the town. In the narrow
      streets with their old-time houses the men wear big hats, embroidered
      waistcoats and four coats, one on top of the other; the inside one, as
      large as your hand, barely covering the shoulder-blades, and the outside
      one coming to just above the seat of the trousers.

“The girls, tall, handsome and fresh have their bosoms crushed in a
      cloth bodice which makes an armor, compresses them, not allowing one even
      to guess at their robust and tortured neck. They also wear a strange
      headdress. On their temples two bands embroidered in colors frame their
      face, inclosing the hair, which falls in a shower at the back of their
      heads, and is then turned up and gathered on top of the head under a
      singular cap, often woven with gold or silver thread.

“The servant at our inn was eighteen at most, with very blue eyes, a
      pale blue with two tiny black pupils, short teeth close together, which
      she showed continually when she laughed, and which seemed strong enough to
      grind granite.

“As my friend did not improve much, and although he had no definite
      malady, the doctor forbade him to continue his journey yet, ordering
      complete rest. I spent my days with him, and the little maid would come in
      incessantly, bringing either my dinner or some herb tea.

“I teased her a little, which seemed to amuse her, but we did not
      chat, of course, as we could not understand each other.

“But one night, after I had stayed quite late with my friend and was
      going back to my room, I passed the girl, who was going to her room. It
      was just opposite my open door, and, without reflection, and more for fun
      than anything else, I abruptly seized her round the waist, and before she
      recovered from her astonishment I had thrown her down and locked her in my
      room. She looked at me, amazed, excited, terrified, not daring to cry out
      for fear of a scandal and of being probably driven out, first by her
      employers and then, perhaps, by her father.

“I did it as a joke at first. She defended herself bravely, and at
      the first chance she ran to the door, drew back the bolt and fled.

“I scarcely saw her for several days. She would not let me come near
      her. But when my friend was cured and we were to get out on our travels
      again I saw her coming into my room about midnight the night before our
      departure, just after I had retired.

“She threw herself into my arms and embraced me passionately, giving
      me all the assurances of tenderness and despair that a woman can give when
      she does not know a word of our language.

“A week later I had forgotten this adventure, so common and frequent
      when one is travelling, the inn servants being generally destined to amuse
      travellers in this way.

“But in 1876 I revisited it by chance during a trip into Brittany,
      which I made in order to look up some data for a book and to become
      permeated with the atmosphere of the different places.

“Nothing seemed changed. The chateau still laved its gray wall in
      the pond outside the little town; the inn was the same, though it had been
      repaired, renovated and looked more modern. As I entered it I was received
      by two young Breton girls of eighteen, fresh and pretty, bound up in their
      tight cloth bodices, with their silver caps and wide embroidered bands on
      their ears.

“It was about six o''clock in the evening. I sat down to dinner, and
      as the host was assiduous in waiting on me himself, fate, no doubt,
      impelled me to say:

“''Did you know the former proprietors of this house? I spent about
      ten days here thirty years ago. I am talking old times.''

“Then I told him why we had stayed over at that time, how my comrade
      had been delayed by illness. He did not let me finish.

“''Oh, I recollect perfectly. I was about fifteen or sixteen. You
      slept in the room at the end and your friend in the one I have taken for
      myself, overlooking the street.''

“It was only then that the recollection of the little maid came
      vividly to my mind. I asked: ''Do you remember a pretty little servant who
      was then in your father''s employ, and who had, if my memory does not
      deceive me, pretty eyes and fresh-looking teeth?''

“''He is not handsome and does not look much like his mother. No
      doubt he looks like his father.''

“''That is very possible,'' replied the innkeeper; ''but we never knew
      whose child it was. She died without telling any one, and no one here knew
      of her having a beau. Every one was hugely astonished when they heard she
      was enceinte, and no one would believe it.''

“A sort of unpleasant chill came over me, one of those painful
      surface wounds that affect us like the shadow of an impending sorrow. And
      I looked at the man in the yard. He had just drawn water for the horses
      and was carrying two buckets, limping as he walked, with a painful effort
      of his shorter leg. His clothes were ragged, he was hideously dirty, with
      long yellow hair, so tangled that it looked like strands of rope falling
      down at either side of his face.

“''He is not worth much,'' continued the innkeeper; ''we have kept him
      for charity''s sake. Perhaps he would have turned out better if he had been
      brought up like other folks. But what could one do, monsieur? No father,
      no mother, no money! My parents took pity on him, but he was not their
      child, you understand.''

“I slept in my old room, and all night long I thought of this
      frightful stableman, saying to myself: ''Supposing it is my own son? Could
      I have caused that girl''s death and procreated this being? It was quite
      possible!''

“I resolved to speak to this man and to find out the exact date of
      his birth. A variation of two months would set my doubts at rest.

“I sent for him the next day. But he could not speak French. He
      looked as if he could not understand anything, being absolutely ignorant
      of his age, which I had inquired of him through one of the maids. He stood
      before me like an idiot, twirling his hat in ''his knotted, disgusting
      hands, laughing stupidly, with something of his mother''s laugh in the
      corners of his mouth and of his eyes.

“The landlord, appearing on the scene, went to look for the birth
      certificate of this wretched being. He was born eight months and
      twenty-six days after my stay at Pont Labbe, for I recollect perfectly
      that we reached Lorient on the fifteenth of August. The certificate
      contained this description: ''Father unknown.'' The mother called herself
      Jeanne Kerradec.

“Then my heart began to beat rapidly. I could not utter a word, for
      I felt as if I were choking. I looked at this animal whose long yellow
      hair reminded me of a straw heap, and the beggar, embarrassed by my gaze,
      stopped laughing, turned his head aside, and wanted to get away.

“All day long I wandered beside the little river, giving way to
      painful reflections. But what was the use of reflection? I could be sure
      of nothing. For hours and hours I weighed all the pros and cons in favor
      of or against the probability of my being the father, growing nervous over
      inexplicable suppositions, only to return incessantly to the same horrible
      uncertainty, then to the still more atrocious conviction that this man was
      my son.

“I lay awake for a long time, and when I finally fell asleep I was
      haunted by horrible visions. I saw this laborer laughing in my face and
      calling me ''papa.'' Then he changed into a dog and bit the calves of my
      legs, and no matter how fast I ran he still followed me, and instead of
      barking, talked and reviled me. Then he appeared before my colleagues at
      the Academy, who had assembled to decide whether I was really his father;
      and one of them cried out: ''There can be no doubt about it! See how he
      resembles him.'' And, indeed, I could see that this monster looked like me.
      And I awoke with this idea fixed in my mind and with an insane desire to
      see the man again and assure myself whether or not we had similar
      features.

“I joined him as he was going to mass (it was Sunday) and I gave him
      five francs as I gazed at him anxiously. He began to laugh in an idiotic
      manner, took the money, and then, embarrassed afresh at my gaze, he ran
      off, after stammering an almost inarticulate word that, no doubt, meant
      ''thank you.''

“My day passed in the same distress of mind as on the previous
      night. I sent for the landlord, and, with the greatest caution, skill and
      tact, I told him that I was interested in this poor creature, so abandoned
      by every one and deprived of everything, and I wished to do something for
      him.

“But the man replied: ''Oh, do not think of it, monsieur; he is of no
      account; you will only cause yourself annoyance. I employ him to clean out
      the stable, and that is all he can do. I give him his board and let him
      sleep with the horses. He needs nothing more. If you have an old pair of
      trousers, you might give them to him, but they will be in rags in a week.''

“The poor wretch came home that evening frightfully drunk, came near
      setting fire to the house, killed a horse by hitting it with a pickaxe,
      and ended up by lying down to sleep in the mud in the midst of the pouring
      rain, thanks to my donation.

“They begged me next day not to give him any more money. Brandy
      drove him crazy, and as soon as he had two sous in his pocket he would
      spend it in drink. The landlord added: ''Giving him money is like trying to
      kill him.'' The man had never, never in his life had more than a few
      centimes, thrown to him by travellers, and he knew of no destination for
      this metal but the wine shop.

“I spent several hours in my room with an open book before me which
      I pretended to read, but in reality looking at this animal, my son! my
      son! trying to discover if he looked anything like me. After careful
      scrutiny I seemed to recognize a similarity in the lines of the forehead
      and the root of the nose, and I was soon convinced that there was a
      resemblance, concealed by the difference in garb and the man''s hideous
      head of hair.

“I could not stay here any longer without arousing suspicion, and I
      went away, my heart crushed, leaving with the innkeeper some money to
      soften the existence of his servant.

“For six years now I have lived with this idea in my mind, this
      horrible uncertainty, this abominable suspicion. And each year an
      irresistible force takes me back to Pont Labbe. Every year I condemn
      myself to the torture of seeing this animal raking the manure, imagining
      that he resembles me, and endeavoring, always vainly, to render him some
      assistance. And each year I return more uncertain, more tormented, more
      worried.

“I tried to have him taught, but he is a hopeless idiot. I tried to
      make his life less hard. He is an irreclaimable drunkard, and spends in
      drink all the money one gives him, and knows enough to sell his new
      clothes in order to get brandy.

“I tried to awaken his master''s sympathy, so that he should look
      after him, offering to pay him for doing so. The innkeeper, finally
      surprised, said, very wisely: ''All that you do for him, monsieur, will
      only help to destroy him. He must be kept like a prisoner. As soon as he
      has any spare time, or any comfort, he becomes wicked. If you wish to do
      good, there is no lack of abandoned children, but select one who will
      appreciate your attention.''

“If I allowed the slightest suspicion of the doubts that tortured me
      to escape, this idiot would assuredly become cunning, in order to
      blackmail me, to compromise me and ruin me. He would call out ''papa,'' as
      in my dream.

“And I said to myself that I had killed the mother and lost this
      atrophied creature, this larva of the stable, born and raised amid the
      manure, this man who, if brought up like others, would have been like
      others.

“And you cannot imagine what a strange, embarrassed and intolerable
      feeling comes over me when he stands before me and I reflect that he came
      from myself, that he belongs to me through the intimate bond that links
      father and son, that, thanks to the terrible law of heredity, he is my own
      self in a thousand ways, in his blood and his flesh, and that he has even
      the same germs of disease, the same leaven of emotions.

“I have an incessant restless, distressing longing to see him, and
      the sight of him causes me intense suffering, as I look down from my
      window and watch him for hours removing and carting the horse manure,
      saying to myself: ''That is my son.''

“And I sometimes feel an irresistible longing to embrace him. I have
      never even touched his dirty hand.”

The academician was silent. His companion, a tactful man, murmured:
      “Yes, indeed, we ought to take a closer interest in children who
      have no father.”

A gust of wind passing through the tree shook its yellow clusters,
      enveloping in a fragrant and delicate mist the two old men, who inhaled in
      the fragrance with deep breaths.

“Here, my friend,” I said to Labarbe, “you have just
      repeated those five words, that pig of a Morin. Why on earth do I never
      hear Morin''s name mentioned without his being called a pig?”

Labarbe, who is a deputy, looked at me with his owl-like eyes and said:
      “Do you mean to say that you do not know Morin''s story and you come
      from La Rochelle?” I was obliged to declare that I did not know
      Morin''s story, so Labarbe rubbed his hands and began his recital.

“You knew Morin, did you not, and you remember his large
      linen-draper''s shop on the Quai de la Rochelle?”

“Well, then. You must know that in 1862 or ''63 Morin went to spend a
      fortnight in Paris for pleasure; or for his pleasures, but under the
      pretext of renewing his stock, and you also know what a fortnight in Paris
      means to a country shopkeeper; it fires his blood. The theatre every
      evening, women''s dresses rustling up against you and continual excitement;
      one goes almost mad with it. One sees nothing but dancers in tights,
      actresses in very low dresses, round legs, fat shoulders, all nearly
      within reach of one''s hands, without daring, or being able, to touch them,
      and one scarcely tastes food. When one leaves the city one''s heart is
      still all in a flutter and one''s mind still exhilarated by a sort of
      longing for kisses which tickles one''s lips.

“Morin was in that condition when he took his ticket for La Rochelle
      by the eight-forty night express. As he was walking up and down the
      waiting-room at the station he stopped suddenly in front of a young lady
      who was kissing an old one. She had her veil up, and Morin murmured with
      delight: ''By Jove what a pretty woman!''

“When she had said ''good-by'' to the old lady she went into the
      waiting-room, and Morin followed her; then she went on the platform and
      Morin still followed her; then she got into an empty carriage, and he
      again followed her. There were very few travellers on the express. The
      engine whistled and the train started. They were alone. Morin devoured her
      with his eyes. She appeared to be about nineteen or twenty and was fair,
      tall, with a bold look. She wrapped a railway rug round her and stretched
      herself on the seat to sleep.

“Morin asked himself: ''I wonder who she is?'' And a thousand
      conjectures, a thousand projects went through his head. He said to
      himself: ''So many adventures are told as happening on railway journeys
      that this may be one that is going to present itself to me. Who knows? A
      piece of good luck like that happens very suddenly, and perhaps I need
      only be a little venturesome. Was it not Danton who said: “Audacity,
      more audacity and always audacity”? If it was not Danton it was
      Mirabeau, but that does not matter. But then I have no audacity, and that
      is the difficulty. Oh! If one only knew, if one could only read people''s
      minds! I will bet that every day one passes by magnificent opportunities
      without knowing it, though a gesture would be enough to let me know her
      mind.''

“Then he imagined to himself combinations which conducted him to
      triumph. He pictured some chivalrous deed or merely some slight service
      which he rendered her, a lively, gallant conversation which ended in a
      declaration.

“But he could find no opening, had no pretext, and he waited for
      some fortunate circumstance, with his heart beating and his mind
      topsy-turvy. The night passed and the pretty girl still slept, while Morin
      was meditating his own fall. The day broke and soon the first ray of
      sunlight appeared in the sky, a long, clear ray which shone on the face of
      the sleeping girl and woke her. She sat up, looked at the country, then at
      Morin and smiled. She smiled like a happy woman, with an engaging and
      bright look, and Morin trembled. Certainly that smile was intended for
      him; it was discreet invitation, the signal which he was waiting for. That
      smile meant to say: ''How stupid, what a ninny, what a dolt, what a donkey
      you are, to have sat there on your seat like a post all night!

“''Just look at me, am I not charming? And you have sat like that for
      the whole night, when you have been alone with a pretty woman, you great
      simpleton!''

“She was still smiling as she looked at him; she even began to
      laugh; and he lost his head trying to find something suitable to say, no
      matter what. But he could think of nothing, nothing, and then, seized with
      a coward''s courage, he said to himself:

“''So much the worse, I will risk everything,'' and suddenly, without
      the slightest warning, he went toward her, his arms extended, his lips
      protruding, and, seizing her in his arms, he kissed her.

“She sprang up immediately with a bound, crying out: ''Help! help!''
      and screaming with terror; and then she opened the carriage door and waved
      her arm out, mad with terror and trying to jump out, while Morin, who was
      almost distracted and feeling sure that she would throw herself out, held
      her by the skirt and stammered: ''Oh, madame! oh, madame!''

“The train slackened speed and then stopped. Two guards rushed up at
      the young woman''s frantic signals. She threw herself into their arms,
      stammering: ''That man wanted—wanted—to—to—'' And
      then she fainted.

“They were at Mauze station, and the gendarme on duty arrested
      Morin. When the victim of his indiscreet admiration had regained her
      consciousness, she made her charge against him, and the police drew it up.
      The poor linen draper did not reach home till night, with a prosecution
      hanging over him for an outrage to morals in a public place.” II

“At that time I was editor of the Fanal des Charentes, and I used to
      meet Morin every day at the Cafe du Commerce, and the day after his
      adventure. he came to see me, as he did not know what to do. I did not
      hide my opinion from him, but said to him: ''You are no better than a pig.
      No decent man behaves like that.''

“He cried. His wife had given him a beating, and he foresaw his
      trade ruined, his name dragged through the mire and dishonored, his
      friends scandalized and taking no notice of him. In the end he excited my
      pity, and I sent for my colleague, Rivet, a jocular but very sensible
      little man, to give us his advice.

“He advised me to see the public prosecutor, who was a friend of
      mine, and so I sent Morin home and went to call on the magistrate. He told
      me that the woman who had been insulted was a young lady, Mademoiselle
      Henriette Bonnel, who had just received her certificate as governess in
      Paris and spent her holidays with her uncle and aunt, who were very
      respectable tradespeople in Mauze. What made Morin''s case all the more
      serious was that the uncle had lodged a complaint, but the public official
      had consented to let the matter drop if this complaint were withdrawn, so
      we must try and get him to do this.

“I went back to Morin''s and found him in bed, ill with excitement
      and distress. His wife, a tall raw-boned woman with a beard, was abusing
      him continually, and she showed me into the room, shouting at me: ''So you
      have come to see that pig of a Morin. Well, there he is, the darling!'' And
      she planted herself in front of the bed, with her hands on her hips. I
      told him how matters stood, and he begged me to go and see the girl''s
      uncle and aunt. It was a delicate mission, but I undertook it, and the
      poor devil never ceased repeating: ''I assure you I did not even kiss her;
      no, not even that. I will take my oath to it!''

“I replied: ''It is all the same; you are nothing but a pig.'' And I
      took a thousand francs which he gave me to employ as I thought best, but
      as I did not care to venture to her uncle''s house alone, I begged Rivet to
      go with me, which he agreed to do on condition that we went immediately,
      for he had some urgent business at La Rochelle that afternoon. So two
      hours later we rang at the door of a pretty country house. An attractive
      girl came and opened the door to us assuredly the young lady in question,
      and I said to Rivet in a low voice: ''Confound it! I begin to understand
      Morin!''

“The uncle, Monsieur Tonnelet, subscribed to the Fanal, and was a
      fervent political coreligionist of ours. He received us with open arms and
      congratulated us and wished us joy; he was delighted at having the two
      editors in his house, and Rivet whispered to me: ''I think we shall be able
      to arrange the matter of that pig of a Morin for him.''

“The niece had left the room and I introduced the delicate subject.
      I waved the spectre of scandal before his eyes; I accentuated the
      inevitable depreciation which the young lady would suffer if such an
      affair became known, for nobody would believe in a simple kiss, and the
      good man seemed undecided, but he could not make up his mind about
      anything without his wife, who would not be in until late that evening.
      But suddenly he uttered an exclamation of triumph: ''Look here, I have an
      excellent idea; I will keep you here to dine and sleep, and when my wife
      comes home I hope we shall be able to arrange matters:

“Rivet resisted at first, but the wish to extricate that pig of a
      Morin decided him, and we accepted the invitation, and the uncle got up
      radiant, called his niece and proposed that we should take a stroll in his
      grounds, saying: ''We will leave serious matters until the morning.'' Rivet
      and he began to talk politics, while I soon found myself lagging a little
      behind with ''the girl who was really charming—charming—and
      with the greatest precaution I began to speak to her about her adventure
      and try to make her my ally. She did not, however, appear the least
      confused, and listened to me like a person who was enjoying the whole
      thing very much.

“I said to her: ''Just think, mademoiselle, how unpleasant it will be
      for you. You will have to appear in court, to encounter malicious looks,
      to speak before everybody and to recount that unfortunate occurrence in
      the railway carriage in public. Do you not think, between ourselves, that
      it would have been much better for you to have put that dirty scoundrel
      back in his place without calling for assistance, and merely to change
      your carriage?'' She began to laugh and replied: ''What you say is quite
      true, but what could I do? I was frightened, and when one is frightened
      one does not stop to reason with one''s self. As soon as I realized the
      situation I was very sorry, that I had called out, but then it was too
      late. You must also remember that the idiot threw himself upon me like a
      madman, without saying a word and looking like a lunatic. I did not even
      know what he wanted of me.''

“She looked me full in the face without being nervous or intimidated
      and I said to myself: ''She is a queer sort of girl, that: I can quite see
      how that pig Morin came to make a mistake,'' and I went on jokingly: ''Come,
      mademoiselle, confess that he was excusable, for, after all, a man cannot
      find himself opposite such a pretty girl as you are without feeling a
      natural desire to kiss her.''

“She laughed more than ever and showed her teeth and said: ''Between
      the desire and the act, monsieur, there is room for respect.'' It was an
      odd expression to use, although it was not very clear, and I asked
      abruptly: ''Well, now, suppose I were to kiss you, what would you do?'' She
      stopped to look at me from head to foot and then said calmly: ''Oh, you?
      That is quite another matter.''

“I knew perfectly well, by Jove, that it was not the same thing at
      all, as everybody in the neighborhood called me ''Handsome Labarbe''—I
      was thirty years old in those days—but I asked her: ''And why, pray?''
      She shrugged her shoulders and replied: ''Well! because you are not so
      stupid as he is.'' And then she added, looking at me slyly: ''Nor so ugly,
      either: And before she could make a movement to avoid me I had implanted a
      hearty kiss on her cheek. She sprang aside, but it was too late, and then
      she said: ''Well, you are not very bashful, either! But don''t do that sort
      of thing again.''

“I put on a humble look and said in a low voice: ''Oh, mademoiselle!
      as for me, if I long for one thing more than another it is to be summoned
      before a magistrate for the same reason as Morin.''

“''Why?'' she asked. And, looking steadily at her, I replied: ''Because
      you are one of the most beautiful creatures living; because it would be an
      honor and a glory for me to have wished to offer you violence, and because
      people would have said, after seeing you: “Well, Labarbe has richly
      deserved what he has got, but he is a lucky fellow, all the same.”''

“She began to laugh heartily again and said: ''How funny you are!''
      And she had not finished the word ''funny'' before I had her in my arms and
      was kissing her ardently wherever I could find a place, on her forehead,
      on her eyes, on her lips occasionally, on her cheeks, all over her head,
      some part of which she was obliged to leave exposed, in spite of herself,
      to defend the others; but at last she managed to release herself, blushing
      and angry. ''You are very unmannerly, monsieur,'' she said, ''and I am sorry
      I listened to you.''

“I took her hand in some confusion and stammered out: ''I beg your
      pardon. I beg your pardon, mademoiselle. I have offended you; I have acted
      like a brute! Do not be angry with me for what I have done. If you knew—''
      I vainly sought for some excuse, and in a few moments she said: ''There is
      nothing for me to know, monsieur.'' But I had found something to say, and I
      cried: ''Mademoiselle, I love you!''

“She was really surprised and raised her eyes to look at me, and I
      went on: ''Yes, mademoiselle, and pray listen to me. I do not know Morin,
      and I do not care anything about him. It does not matter to me the least
      if he is committed for trial and locked up meanwhile. I saw you here last
      year, and I was so taken with you that the thought of you has never left
      me since, and it does not matter to me whether you believe me or not. I
      thought you adorable, and the remembrance of you took such a hold on me
      that I longed to see you again, and so I made use of that fool Morin as a
      pretext, and here I am. Circumstances have made me exceed the due limits
      of respect, and I can only beg you to pardon me.''

“She looked at me to see if I was in earnest and was ready to smile
      again. Then she murmured: ''You humbug!'' But I raised my hand and said in a
      sincere voice (and I really believe that I was sincere): ''I swear to you
      that I am speaking the truth,'' and she replied quite simply: ''Don''t talk
      nonsense!''

“We were alone, quite alone, as Rivet and her uncle had disappeared
      down a sidewalk, and I made her a real declaration of love, while I
      squeezed and kissed her hands, and she listened to it as to something new
      and agreeable, without exactly knowing how much of it she was to believe,
      while in the end I felt agitated, and at last really myself believed what
      I said. I was pale, anxious and trembling, and I gently put my arm round
      her waist and spoke to her softly, whispering into the little curls over
      her ears. She seemed in a trance, so absorbed in thought was she.

“Then her hand touched mine, and she pressed it, and I gently
      squeezed her waist with a trembling, and gradually firmer, grasp. She did
      not move now, and I touched her cheek with my lips, and suddenly without
      seeking them my lips met hers. It was a long, long kiss, and it would have
      lasted longer still if I had not heard a hm! hm! just behind me, at which
      she made her escape through the bushes, and turning round I saw Rivet
      coming toward me, and, standing in the middle of the path, he said without
      even smiling: ''So that is the way you settle the affair of that pig of a
      Morin.'' And I replied conceitedly: ''One does what one can, my dear fellow.
      But what about the uncle? How have you got on with him? I will answer for
      the niece.'' ''I have not been so fortunate with him,'' he replied.

“Dinner made me lose my head altogether. I sat beside her, and my
      hand continually met hers under the tablecloth, my foot touched hers and
      our glances met.

“After dinner we took a walk by moonlight, and I whispered all the
      tender things I could think of to her. I held her close to me, kissed her
      every moment, while her uncle and Rivet were arguing as they walked in
      front of us. They went in, and soon a messenger brought a telegram from
      her aunt, saying that she would not return until the next morning at seven
      o''clock by the first train.

“''Very well, Henriette,'' her uncle said, ''go and show the gentlemen
      their rooms.'' She showed Rivet his first, and he whispered to me: ''There
      was no danger of her taking us into yours first.'' Then she took me to my
      room, and as soon as she was alone with me I took her in my arms again and
      tried to arouse her emotion, but when she saw the danger she escaped out
      of the room, and I retired very much put out and excited and feeling
      rather foolish, for I knew that I should not sleep much, and I was
      wondering how I could have committed such a mistake, when there was a
      gentle knock at my door, and on my asking who was there a low voice
      replied: ''I''

“I dressed myself quickly and opened the door, and she came in. ''I
      forgot to ask you what you take in the morning,'' she said; ''chocolate, tea
      or coffee?'' I put my arms round her impetuously and said, devouring her
      with kisses: ''I will take—I will take—''

“But she freed herself from my arms, blew out my candle and
      disappeared and left me alone in the dark, furious, trying to find some
      matches, and not able to do so. At last I got some and I went into the
      passage, feeling half mad, with my candlestick in my hand.

“What was I about to do? I did not stop to reason, I only wanted to
      find her, and I would. I went a few steps without reflecting, but then I
      suddenly thought: ''Suppose I should walk into the uncle''s room what should
      I say?'' And I stood still, with my head a void and my heart beating. But
      in a few moments I thought of an answer: ''Of course, I shall say that I
      was looking for Rivet''s room to speak to him about an important matter,''
      and I began to inspect all the doors, trying to find hers, and at last I
      took hold of a handle at a venture, turned it and went in. There was
      Henriette, sitting on her bed and looking at me in tears. So I gently
      turned the key, and going up to her on tiptoe I said: ''I forgot to ask you
      for something to read, mademoiselle.''

“I was stealthily returning to my room when a rough hand seized me
      and a voice—it was Rivet''s—whispered in my ear: ''So you have
      not yet quite settled that affair of Morin''s?''

“At seven o''clock the next morning Henriette herself brought me a
      cup of chocolate. I never have drunk anything like it, soft, velvety,
      perfumed, delicious. I could hardly take away my lips from the cup, and
      she had hardly left the room when Rivet came in. He seemed nervous and
      irritable, like a man who had not slept, and he said to me crossly:

“At eight o''clock the aunt arrived. Our discussion was very short,
      for they withdrew their complaint, and I left five hundred francs for the
      poor of the town. They wanted to keep us for the day, and they arranged an
      excursion to go and see some ruins. Henriette made signs to me to stay,
      behind her parents'' back, and I accepted, but Rivet was determined to go,
      and though I took him aside and begged and prayed him to do this for me,
      he appeared quite exasperated and kept saying to me: ''I have had enough of
      that pig of a Morin''s affair, do you hear?''

“Of course I was obliged to leave also, and it was one of the
      hardest moments of my life. I could have gone on arranging that business
      as long as I lived, and when we were in the railway carriage, after
      shaking hands with her in silence, I said to Rivet: ''You are a mere
      brute!'' And he replied: ''My dear fellow, you were beginning to annoy me
      confoundedly.''

“On getting to the Fanal office, I saw a crowd waiting for us, and
      as soon as they saw us they all exclaimed: ''Well, have you settled the
      affair of that pig of a Morin?'' All La Rochelle was excited about it, and
      Rivet, who had got over his ill-humor on the journey, had great difficulty
      in keeping himself from laughing as he said: ''Yes, we have managed it,
      thanks to Labarbe: And we went to Morin''s.

“He was sitting in an easy-chair with mustard plasters on his legs
      and cold bandages on his head, nearly dead with misery. He was coughing
      with the short cough of a dying man, without any one knowing how he had
      caught it, and his wife looked at him like a tigress ready to eat him, and
      as soon as he saw us he trembled so violently as to make his hands and
      knees shake, so I said to him immediately: ''It is all settled, you dirty
      scamp, but don''t do such a thing again.''

“He got up, choking, took my hands and kissed them as if they had
      belonged to a prince, cried, nearly fainted, embraced Rivet and even
      kissed Madame Morin, who gave him such a push as to send him staggering
      back into his chair; but he never got over the blow; his mind had been too
      much upset. In all the country round, moreover, he was called nothing but
      ''that pig of a Morin,'' and that epithet went through him like a
      sword-thrust every time he heard it. When a street boy called after him
      ''Pig!'' he turned his head instinctively. His friends also overwhelmed him
      with horrible jokes and used to ask him, whenever they were eating ham,
      ''Is it a bit of yourself?'' He died two years later.

“As for myself, when I was a candidate for the Chamber of Deputies
      in 1875, I called on the new notary at Fousserre, Monsieur Belloncle, to
      solicit his vote, and a tall, handsome and evidently wealthy lady received
      me. ''You do not know me again?'' she said. And I stammered out: ''Why—no—madame.''
      ''Henriette Bonnel.'' ''Ah!'' And I felt myself turning pale, while she seemed
      perfectly at her ease and looked at me with a smile.

“As soon as she had left me alone with her husband he took both my
      hands, and, squeezing them as if he meant to crush them, he said: ''I have
      been intending to go and see you for a long time, my dear sir, for my wife
      has very often talked to me about you. I know—yes, I know under what
      painful circumstances you made her acquaintance, and I know also how
      perfectly you behaved, how full of delicacy, tact and devotion you showed
      yourself in the affair—'' He hesitated and then said in a lower tone,
      as if he had been saying something low and coarse, ''in the affair of that
      pig of a Morin.''”

They called him Saint Anthony, because his name was Anthony, and also,
      perhaps, because he was a good fellow, jovial, a lover of practical jokes,
      a tremendous eater and a heavy drinker and a gay fellow, although he was
      sixty years old.

He was a big peasant of the district of Caux, with a red face, large chest
      and stomach, and perched on two legs that seemed too slight for the bulk
      of his body.

He was a widower and lived alone with his two men servants and a maid on
      his farm, which he conducted with shrewd economy. He was careful of his
      own interests, understood business and the raising of cattle, and farming.
      His two sons and his three daughters, who had married well, were living in
      the neighborhood and came to dine with their father once a month. His
      vigor of body was famous in all the countryside. “He is as strong as
      Saint Anthony,” had become a kind of proverb.

At the time of the Prussian invasion Saint Anthony, at the wine shop,
      promised to eat an army, for he was a braggart, like a true Norman, a bit
      of a coward and a blusterer. He banged his fist on the wooden table,
      making the cups and the brandy glasses dance, and cried with the assumed
      wrath of a good fellow, with a flushed face and a sly look in his eye:
      “I shall have to eat some of them, nom de Dieu!” He reckoned
      that the Prussians would not come as far as Tanneville, but when he heard
      they were at Rautot he never went out of the house, and constantly watched
      the road from the little window of his kitchen, expecting at any moment to
      see the bayonets go by.

One morning as he was eating his luncheon with the servants the door
      opened and the mayor of the commune, Maitre Chicot, appeared, followed by
      a soldier wearing a black copper-pointed helmet. Saint Anthony bounded to
      his feet and his servants all looked at him, expecting to see him slash
      the Prussian. But he merely shook hands with the mayor, who said:

“Here is one for you, Saint Anthony. They came last night. Don''t do
      anything foolish, above all things, for they talked of shooting and
      burning everything if there is the slightest unpleasantness, I have given
      you warning. Give him something to eat; he looks like a good fellow.
      Good-day. I am going to call on the rest. There are enough for all.”
      And he went out.

Father Anthony, who had turned pale, looked at the Prussian. He was a big,
      young fellow with plump, white skin, blue eyes, fair hair, unshaven to his
      cheek bones, who looked stupid, timid and good. The shrewd Norman read him
      at once, and, reassured, he made him a sign to sit down. Then he said:
      “Will you take some soup?”

The stranger did not understand. Anthony then became bolder, and pushing a
      plateful of soup right under his nose, he said: “Here, swallow that,
      big pig!”

The soldier answered “Ya,” and began to eat greedily, while
      the farmer, triumphant, feeling he had regained his reputation, winked his
      eye at the servants, who were making strange grimaces, what with their
      terror and their desire to laugh.

When the Prussian had devoured his soup, Saint Anthony gave him another
      plateful, which disappeared in like manner; but he flinched at the third
      which the farmer tried to insist on his eating, saying: “Come, put
      that into your stomach; ''twill fatten you or it is your own fault, eh,
      pig!”

The soldier, understanding only that they wanted to make him eat all his
      soup, laughed in a contented manner, making a sign to show that he could
      not hold any more.

Then Saint Anthony, become quite familiar, tapped him on the stomach,
      saying: “My, there is plenty in my pig''s belly!” But suddenly
      he began to writhe with laughter, unable to speak. An idea had struck him
      which made him choke with mirth. “That''s it, that''s it, Saint
      Anthony and his pig. There''s my pig!” And the three servants burst
      out laughing in their turn.

The old fellow was so pleased that he had the brandy brought in, good
      stuff, ''fil en dix'', and treated every one. They clinked glasses with the
      Prussian, who clacked his tongue by way of flattery to show that he
      enjoyed it. And Saint Anthony exclaimed in his face: “Eh, is not
      that superfine? You don''t get anything like that in your home, pig!”

From that time Father Anthony never went out without his Prussian. He had
      got what he wanted. This was his vengeance, the vengeance of an old rogue.
      And the whole countryside, which was in terror, laughed to split its sides
      at Saint Anthony''s joke. Truly, there was no one like him when it came to
      humor. No one but he would have thought of a thing like that. He was a
      born joker!

He went to see his neighbors every day, arm in arm with his German, whom
      he introduced in a jovial manner, tapping him on the shoulder: “See,
      here is my pig; look and see if he is not growing fat, the animal!”

And they all winked at each other, but dared not laugh too loud, for fear
      the Prussian might finally suspect they were laughing at him. Anthony,
      alone growing bolder every day, pinched his thighs, exclaiming, “Nothing
      but fat”; tapped him on the back, shouting, “That is all bacon”;
      lifted him up in his arms as an old Colossus that could have lifted an
      anvil, declaring, “He weighs six hundred and no waste.”

He had got into the habit of making people offer his “pig”
      something to eat wherever they went together. This was the chief pleasure,
      the great diversion every day. “Give him whatever you please, he
      will swallow everything.” And they offered the man bread and butter,
      potatoes, cold meat, chitterlings, which caused the remark, “Some of
      your own, and choice ones.”

The soldier, stupid and gentle, ate from politeness, charmed at these
      attentions, making himself ill rather than refuse, and he was actually
      growing fat and his uniform becoming tight for him. This delighted Saint
      Anthony, who said: “You know, my pig, that we shall have to have
      another cage made for you.”

They had, however, become the best friends in the world, and when the old
      fellow went to attend to his business in the neighborhood the Prussian
      accompanied him for the simple pleasure of being with him.

The weather was severe; it was freezing hard. The terrible winter of 1870
      seemed to bring all the scourges on France at one time.

Father Antoine, who made provision beforehand, and took advantage of every
      opportunity, foreseeing that manure would be scarce for the spring
      farming, bought from a neighbor who happened to be in need of money all
      that he had, and it was agreed that he should go every evening with his
      cart to get a load.

So every day at twilight he set out for the farm of Haules, half a league
      distant, always accompanied by his “pig.” And each time it was
      a festival, feeding the animal. All the neighbors ran over there as they
      would go to high mass on Sunday.

But the soldier began to suspect something, be mistrustful, and when they
      laughed too loud he would roll his eyes uneasily, and sometimes they
      lighted up with anger.

One evening when he had eaten his fill he refused to swallow another
      morsel, and attempted to rise to leave the table. But Saint Anthony
      stopped him by a turn of the wrist and, placing his two powerful hands on
      his shoulders, he sat him down again so roughly that the chair smashed
      under him.

A wild burst of laughter broke forth, and Anthony, beaming, picked up his
      pig, acted as though he were dressing his wounds, and exclaimed: “Since
      you will not eat, you shall drink, nom de Dieu!” And they went to
      the wine shop to get some brandy.

The soldier rolled his eyes, which had a wicked expression, but he drank,
      nevertheless; he drank as long as they wanted him, and Saint Anthony held
      his head to the great delight of his companions.

The Norman, red as a tomato, his eyes ablaze, filled up the glasses and
      clinked, saying: “Here''s to you!”. And the Prussian, without
      speaking a word, poured down one after another glassfuls of cognac.

It was a contest, a battle, a revenge! Who would drink the most, nom d''un
      nom! They could neither of them stand any more when the liter was emptied.
      But neither was conquered. They were tied, that was all. They would have
      to begin again the next day.

They went out staggering and started for home, walking beside the dung
      cart which was drawn along slowly by two horses.

Snow began to fall and the moonless night was sadly lighted by this dead
      whiteness on the plain. The men began to feel the cold, and this
      aggravated their intoxication. Saint Anthony, annoyed at not being the
      victor, amused himself by shoving his companion so as to make him fall
      over into the ditch. The other would dodge backwards, and each time he did
      he uttered some German expression in an angry tone, which made the peasant
      roar with laughter. Finally the Prussian lost his temper, and just as
      Anthony was rolling towards him he responded with such a terrific blow
      with his fist that the Colossus staggered.

Then, excited by the brandy, the old man seized the pugilist round the
      waist, shook him for a few moments as he would have done with a little
      child, and pitched him at random to the other side of the road. Then,
      satisfied with this piece of work, he crossed his arms and began to laugh
      afresh.

But the soldier picked himself up in a hurry, his head bare, his helmet
      having rolled off, and drawing his sword he rushed over to Father Anthony.

When he saw him coming the peasant seized his whip by the top of the
      handle, his big holly wood whip, straight, strong and supple as the sinew
      of an ox.

The Prussian approached, his head down, making a lunge with his sword,
      sure of killing his adversary. But the old fellow, squarely hitting the
      blade, the point of which would have pierced his stomach, turned it aside,
      and with the butt end of the whip struck the soldier a sharp blow on the
      temple and he fell to the ground.

Then he, gazed aghast, stupefied with amazement, at the body, twitching
      convulsively at first and then lying prone and motionless. He bent over
      it, turned it on its back, and gazed at it for some time. The man''s eyes
      were closed, and blood trickled from a wound at the side of his forehead.
      Although it was dark, Father Anthony could distinguish the bloodstain on
      the white snow.

What was he to do? He would be shot! They would burn his farm, ruin his
      district! What should he do? What should he do? How could he hide the
      body, conceal the fact of his death, deceive the Prussians? He heard
      voices in the distance, amid the utter stillness of the snow. All at once
      he roused himself, and picking up the helmet he placed it on his victim''s
      head. Then, seizing him round the body, he lifted him up in his arms, and
      thus running with him, he overtook his team, and threw the body on top of
      the manure. Once in his own house he would think up some plan.

He walked slowly, racking his brain, but without result. He saw, he felt,
      that he was lost. He entered his courtyard. A light was shining in one of
      the attic windows; his maid was not asleep. He hastily backed his wagon to
      the edge of the manure hollow. He thought that by overturning the manure
      the body lying on top of it would fall into the ditch and be buried
      beneath it, and he dumped the cart.

As he had foreseen, the man was buried beneath the manure. Anthony evened
      it down with his fork, which he stuck in the ground beside it. He called
      his stableman, told him to put up the horses, and went to his room.

He went to bed, still thinking of what he had best do, but no ideas came
      to him. His apprehension increased in the quiet of his room. They would
      shoot him! He was bathed in perspiration from fear, his teeth chattered,
      he rose shivering, not being able to stay in bed.

He went downstairs to the kitchen, took the bottle of brandy from the
      sideboard and carried it upstairs. He drank two large glasses, one after
      another, adding a fresh intoxication to the late one, without quieting his
      mental anguish. He had done a pretty stroke of work, nom de Dieu, idiot!

He paced up and down, trying to think of some stratagem, some
      explanations, some cunning trick, and from time to time he rinsed his
      mouth with a swallow of “fil en dix” to give him courage.

Towards midnight his watch dog, a kind of cross wolf called “Devorant,”
      began to howl frantically. Father Anthony shuddered to the marrow of his
      bones, and each time the beast began his long and lugubrious wail the old
      man''s skin turned to goose flesh.

He had sunk into a chair, his legs weak, stupefied, done up, waiting
      anxiously for “Devorant” to set up another howl, and starting
      convulsively from nervousness caused by terror.

The clock downstairs struck five. The dog was still howling. The peasant
      was almost insane. He rose to go and let the dog loose, so that he should
      not hear him. He went downstairs, opened the hall door, and stepped out
      into the darkness. The snow was still falling. The earth was all white,
      the farm buildings standing out like black patches. He approached the
      kennel. The dog was dragging at his chain. He unfastened it. “Devorant”
      gave a bound, then stopped short, his hair bristling, his legs rigid, his
      muzzle in the air, his nose pointed towards the manure heap.

“What''s the matter with you, you dirty hound?” and he walked a
      few steps forward, gazing at the indistinct outlines, the sombre shadow of
      the courtyard.

He gazed at it, paralyzed by fear, and breathing hard. But all at once he
      saw, close by, the handle of the manure fork which was sticking in the
      ground. He snatched it up and in one of those transports of fear that will
      make the greatest coward brave he rushed forward to see what it was.

It was he, his Prussian, come to life, covered with filth from his bed of
      manure which had kept him warm. He had sat down mechanically, and remained
      there in the snow which sprinkled down, all covered with dirt and blood as
      he was, and still stupid from drinking, dazed by the blow and exhausted
      from his wound.

He perceived Anthony, and too sodden to understand anything, he made an
      attempt to rise. But the moment the old man recognized him, he foamed with
      rage like a wild animal.

And rushing on the German with all the strength of leis arms he flung the
      raised fork like a lance and buried the four prongs full length in his
      breast.

The soldier fell over on his back, uttering a long death moan, while the
      old peasant, drawing the fork out of his breast, plunged it over and over
      again into his abdomen, his stomach, his throat, like a madman, piercing
      the body from head to foot, as it still quivered, and the blood gushed out
      in streams.

Finally he stopped, exhausted by his arduous work, swallowing great
      mouthfuls of air, calmed down at the completion of the murder.

As the cocks were beginning to crow in the poultry yard and it was near
      daybreak, he set to work to bury the man.

He dug a hole in the manure till he reached the earth, dug down further,
      working wildly, in a frenzy of strength with frantic motions of his arms
      and body.

When the pit was deep enough he rolled the corpse into it with the fork,
      covered it with earth, which he stamped down for some time, and then put
      back the manure, and he smiled as he saw the thick snow finishing his work
      and covering up its traces with a white sheet.

He then stuck the fork in the manure and went into the house. His bottle,
      still half full of brandy stood on the table. He emptied it at a draught,
      threw himself on his bed and slept heavily.

At the end of an hour he was going about the country making inquiries
      everywhere for his soldier. He went to see the Prussian officer to find
      out why they had taken away his man.

As everyone knew what good friends they were, no one suspected him. He
      even directed the research, declaring that the Prussian went to see the
      girls every evening.

An old retired gendarme who had an inn in the next village, and a pretty
      daughter, was arrested and shot.

It was the end of the dinner that opened the shooting season. The Marquis
      de Bertrans with his guests sat around a brightly lighted table, covered
      with fruit and flowers. The conversation drifted to love. Immediately
      there arose an animated discussion, the same eternal discussion as to
      whether it were possible to love more than once. Examples were given of
      persons who had loved once; these were offset by those who had loved
      violently many times. The men agreed that passion, like sickness, may
      attack the same person several times, unless it strikes to kill. This
      conclusion seemed quite incontestable. The women, however, who based their
      opinion on poetry rather than on practical observation, maintained that
      love, the great passion, may come only once to mortals. It resembles
      lightning, they said, this love. A heart once touched by it becomes
      forever such a waste, so ruined, so consumed, that no other strong
      sentiment can take root there, not even a dream. The marquis, who had
      indulged in many love affairs, disputed this belief.

“I tell you it is possible to love several times with all one''s
      heart and soul. You quote examples of persons who have killed themselves
      for love, to prove the impossibility of a second passion. I wager that if
      they had not foolishly committed suicide, and so destroyed the possibility
      of a second experience, they would have found a new love, and still
      another, and so on till death. It is with love as with drink. He who has
      once indulged is forever a slave. It is a thing of temperament.”

They chose the old doctor as umpire. He thought it was as the marquis had
      said, a thing of temperament.

“As for me,” he said, “I once knew of a love which
      lasted fifty-five years without one day''s respite, and which ended only
      with death.” The wife of the marquis clasped her hands.

“That is beautiful! Ah, what a dream to be loved in such a way! What
      bliss to live for fifty-five years enveloped in an intense, unwavering
      affection! How this happy being must have blessed his life to be so
      adored!”

“You are not mistaken, madame, on this point the loved one was a
      man. You even know him; it is Monsieur Chouquet, the chemist. As to the
      woman, you also know her, the old chair-mender, who came every year to the
      chateau.” The enthusiasm of the women fell. Some expressed their
      contempt with “Pouah!” for the loves of common people did not
      interest them. The doctor continued: “Three months ago I was called
      to the deathbed of the old chair-mender. The priest had preceded me. She
      wished to make us the executors of her will. In order that we might
      understand her conduct, she told us the story of her life. It is most
      singular and touching: Her father and mother were both chair-menders. She
      had never lived in a house. As a little child she wandered about with
      them, dirty, unkempt, hungry. They visited many towns, leaving their
      horse, wagon and dog just outside the limits, where the child played in
      the grass alone until her parents had repaired all the broken chairs in
      the place. They seldom spoke, except to cry, ''Chairs! Chairs!
      Chair-mender!''

“When the little one strayed too far away, she would be called back
      by the harsh, angry voice of her father. She never heard a word of
      affection. When she grew older, she fetched and carried the broken chairs.
      Then it was she made friends with the children in the street, but their
      parents always called them away and scolded them for speaking to the
      barefooted child. Often the boys threw stones at her. Once a kind woman
      gave her a few pennies. She saved them most carefully.

“One day—she was then eleven years old—as she was
      walking through a country town she met, behind the cemetery, little
      Chouquet, weeping bitterly, because one of his playmates had stolen two
      precious liards (mills). The tears of the small bourgeois, one of those
      much-envied mortals, who, she imagined, never knew trouble, completely
      upset her. She approached him and, as soon as she learned the cause of his
      grief, she put into his hands all her savings. He took them without
      hesitation and dried his eyes. Wild with joy, she kissed him. He was busy
      counting his money, and did not object. Seeing that she was not repulsed,
      she threw her arms round him and gave him a hug—then she ran away.

“What was going on in her poor little head? Was it because she had
      sacrificed all her fortune that she became madly fond of this youngster,
      or was it because she had given him the first tender kiss? The mystery is
      alike for children and for those of riper years. For months she dreamed of
      that corner near the cemetery and of the little chap. She stole a sou here
      and, there from her parents on the chair money or groceries she was sent
      to buy. When she returned to the spot near the cemetery she had two francs
      in her pocket, but he was not there. Passing his father''s drug store, she
      caught sight of him behind the counter. He was sitting between a large red
      globe and a blue one. She only loved him the more, quite carried away at
      the sight of the brilliant-colored globes. She cherished the recollection
      of it forever in her heart. The following year she met him near the school
      playing marbles. She rushed up to him, threw her arms round him, and
      kissed him so passionately that he screamed, in fear. To quiet him, she
      gave him all her money. Three francs and twenty centimes! A real gold
      mine, at which he gazed with staring eyes.

“After this he allowed her to kiss him as much as she wished. During
      the next four years she put into his hands all her savings, which he
      pocketed conscientiously in exchange for kisses. At one time it was thirty
      sous, at another two francs. Again, she only had twelve sous. She wept
      with grief and shame, explaining brokenly that it had been a poor year.
      The next time she brought five francs, in one whole piece, which made her
      laugh with joy. She no longer thought of any one but the boy, and he
      watched for her with impatience; sometimes he would run to meet her. This
      made her heart thump with joy. Suddenly he disappeared. He had gone to
      boarding school. She found this out by careful investigation. Then she
      used great diplomacy to persuade her parents to change their route and
      pass by this way again during vacation. After a year of scheming she
      succeeded. She had not seen him for two years, and scarcely recognized
      him, he was so changed, had grown taller, better looking and was imposing
      in his uniform, with its brass buttons. He pretended not to see her, and
      passed by without a glance. She wept for two days and from that time loved
      and suffered unceasingly.

“Every year he came home and she passed him, not daring to lift her
      eyes. He never condescended to turn his head toward her. She loved him
      madly, hopelessly. She said to me:

“''He is the only man whom I have ever seen. I don''t even know if
      another exists.'' Her parents died. She continued their work.

“One day, on entering the village, where her heart always remained,
      she saw Chouquet coming out of his pharmacy with a young lady leaning on
      his arm. She was his wife. That night the chair-mender threw herself into
      the river. A drunkard passing the spot pulled her out and took her to the
      drug store. Young Chouquet came down in his dressing gown to revive her.
      Without seeming to know who she was he undressed her and rubbed her; then
      he said to her, in a harsh voice:

“''You are mad! People must not do stupid things like that.'' His
      voice brought her to life again. He had spoken to her! She was happy for a
      long time. He refused remuneration for his trouble, although she insisted.

“All her life passed in this way. She worked, thinking always of
      him. She began to buy medicines at his pharmacy; this gave her a chance to
      talk to him and to see him closely. In this way, she was still able to
      give him money.

“As I said before, she died this spring. When she had closed her
      pathetic story she entreated me to take her earnings to the man she loved.
      She had worked only that she might leave him something to remind him of
      her after her death. I gave the priest fifty francs for her funeral
      expenses. The next morning I went to see the Chouquets. They were
      finishing breakfast, sitting opposite each other, fat and red, important
      and self-satisfied. They welcomed me and offered me some coffee, which I
      accepted. Then I began my story in a trembling voice, sure that they would
      be softened, even to tears. As soon as Chouquet understood that he had
      been loved by ''that vagabond! that chair-mender! that wanderer!'' he swore
      with indignation as though his reputation had been sullied, the respect of
      decent people lost, his personal honor, something precious and dearer to
      him than life, gone. His exasperated wife kept repeating: ''That beggar!
      That beggar!''

“Seeming unable to find words suitable to the enormity, he stood up
      and began striding about. He muttered: ''Can you understand anything so
      horrible, doctor? Oh, if I had only known it while she was alive, I should
      have had her thrown into prison. I promise you she would not have
      escaped.''

“I was dumfounded; I hardly knew what to think or say, but I had to
      finish my mission. ''She commissioned me,'' I said, ''to give you her
      savings, which amount to three thousand five hundred francs. As what I
      have just told you seems to be very disagreeable, perhaps you would prefer
      to give this money to the poor.''

“They looked at me, that man and woman,'' speechless with amazement.
      I took the few thousand francs from out of my pocket. Wretched-looking
      money from every country. Pennies and gold pieces all mixed together. Then
      I asked:

“Madame Chouquet spoke first. ''Well, since it is the dying woman''s
      wish, it seems to me impossible to refuse it.''

“He replied: ''Well, give it to us anyhow, since she commissioned you
      to do so; we will find a way to put it to some good purpose.''

“He laughed and held out his hand to me. I shook it. What could I
      do? The doctor and the druggist in a country village must not be at
      enmity. I have kept the dogs. The priest took the old horse. The wagon is
      useful to Chouquet, and with the money he has bought railroad stock. That
      is the only deep, sincere love that I have ever known in all my life.”

Mme. Lefevre was a country dame, a widow, one of these half peasants, with
      ribbons and bonnets with trimming on them, one of those persons who
      clipped her words and put on great airs in public, concealing the soul of
      a pretentious animal beneath a comical and bedizened exterior, just as the
      country-folks hide their coarse red hands in ecru silk gloves.

The two women lived in a little house with green shutters by the side of
      the high road in Normandy, in the centre of the country of Caux. As they
      had a narrow strip of garden in front of the house, they grew some
      vegetables.

One night someone stole twelve onions. As soon as Rose became aware of the
      theft, she ran to tell madame, who came downstairs in her woolen
      petticoat. It was a shame and a disgrace! They had robbed her, Mme.
      Lefevre! As there were thieves in the country, they might come back.

And the two frightened women examined the foot tracks, talking, and
      supposing all sorts of things.

The news of the theft spread. The neighbors came, making examinations and
      discussing the matter in their turn, while the two women explained to each
      newcomer what they had observed and their opinion.

That is true, they ought to have a dog, if it were only to give the alarm.
      Not a big dog. Heavens! what would they do with a big dog? He would eat
      their heads off. But a little dog (in Normandy they say “quin”),
      a little puppy who would bark.

As soon as everyone had left, Mme. Lefevre discussed this idea of a dog
      for some time. On reflection she made a thousand objections, terrified at
      the idea of a bowl full of soup, for she belonged to that race of
      parsimonious country women who always carry centimes in their pocket to
      give alms in public to beggars on the road and to put in the Sunday
      collection plate.

Rose, who loved animals, gave her opinion and defended it shrewdly. So it
      was decided that they should have a dog, a very small dog.

They began to look for one, but could find nothing but big dogs, who would
      devour enough soup to make one shudder. The grocer of Rolleville had one,
      a tiny one, but he demanded two francs to cover the cost of sending it.
      Mme. Lefevre declared that she would feed a “quin,” but would
      not buy one.

The baker, who knew all that occurred, brought in his wagon one morning a
      strange little yellow animal, almost without paws, with the body of a
      crocodile, the head of a fox, and a curly tail—a true cockade, as
      big as all the rest of him. Mme. Lefevre thought this common cur that cost
      nothing was very handsome. Rose hugged it and asked what its name was.

The dog was installed in an old soap box and they gave it some water which
      it drank. They then offered it a piece of bread. He ate it. Mme. Lefevre,
      uneasy, had an idea.

“When he is thoroughly accustomed to the house we can let him run.
      He can find something to eat, roaming about the country.”

They let him run, in fact, which did not prevent him from being famished.
      Also he never barked except to beg for food, and then he barked furiously.

Anyone might come into the garden, and Pierrot would run up and fawn on
      each one in turn and not utter a bark.

Mme. Lefevre, however, had become accustomed to the animal. She even went
      so far as to like it and to give it from time to time pieces of bread
      soaked in the gravy on her plate.

But she had not once thought of the dog tax, and when they came to collect
      eight francs—eight francs, madame—for this puppy who never
      even barked, she almost fainted from the shock.

It was immediately decided that they must get rid of Pierrot. No one
      wanted him. Every one declined to take him for ten leagues around. Then
      they resolved, not knowing what else to do, to make him “piquer du
      mas.”

“Piquer du mas” means to eat chalk. When one wants to get rid
      of a dog they make him “Piquer du mas.”

In the midst of an immense plain one sees a kind of hut, or rather a very
      small roof standing above the ground. This is the entrance to the clay
      pit. A big perpendicular hole is sunk for twenty metres underground and
      ends in a series of long subterranean tunnels.

Once a year they go down into the quarry at the time they fertilize the
      ground. The rest of the year it serves as a cemetery for condemned dogs,
      and as one passed by this hole plaintive howls, furious or despairing
      barks and lamentable appeals reach one''s ear.

Sportsmen''s dogs and sheep dogs flee in terror from this mournful place,
      and when one leans over it one perceives a disgusting odor of
      putrefaction.

When an animal has suffered down there for ten or twelve days, nourished
      on the foul remains of his predecessors, another animal, larger and more
      vigorous, is thrown into the hole. There they are, alone, starving, with
      glittering eyes. They watch each other, follow each other, hesitate in
      doubt. But hunger impels them; they attack each other, fight desperately
      for some time, and the stronger eats the weaker, devours him alive.

When it was decided to make Pierrot “piquer du mas” they
      looked round for an executioner. The laborer who mended the road demanded
      six sous to take the dog there. That seemed wildly exorbitant to Mme.
      Lefevre. The neighbor''s hired boy wanted five sous; that was still too
      much. So Rose having observed that they had better carry it there
      themselves, as in that way it would not be brutally treated on the way and
      made to suspect its fate, they resolved to go together at twilight.

They offered the dog that evening a good dish of soup with a piece of
      butter in it. He swallowed every morsel of it, and as he wagged his tail
      with delight Rose put him in her apron.

They walked quickly, like thieves, across the plain. They soon perceived
      the chalk pit and walked up to it. Mme. Lefevre leaned over to hear if any
      animal was moaning. No, there were none there; Pierrot would be alone.
      Then Rose, who was crying, kissed the dog and threw him into the chalk
      pit, and they both leaned over, listening.

First they heard a dull sound, then the sharp, bitter, distracting cry of
      an animal in pain, then a succession of little mournful cries, then
      despairing appeals, the cries of a dog who is entreating, his head raised
      toward the opening of the pit.

They were filled with remorse, with terror, with a wild inexplicable fear,
      and ran away from the spot. As Rose went faster Mme. Lefevre cried:
      “Wait for me, Rose, wait for me!”

Mme. Lefevre dreamed she was sitting down at table to eat her soup, but
      when she uncovered the tureen Pierrot was in it. He jumped out and bit her
      nose.

She fell asleep again and found herself on a high road, an endless road,
      which she followed. Suddenly in the middle of the road she perceived a
      basket, a large farmer''s basket, lying there, and this basket frightened
      her.

She ended by opening it, and Pierrot, concealed in it, seized her hand and
      would not let go. She ran away in terror with the dog hanging to the end
      of her arm, which he held between his teeth.

He was yelping, yelping still; he had yelped all night. She began to sob
      and called him by all sorts of endearing names. He answered her with all
      the tender inflections of his dog''s voice.

Then she wanted to see him again, promising herself that she would give
      him a good home till he died.

She ran to the chalk digger, whose business it was to excavate for chalk,
      and told him the situation. The man listened, but said nothing. When she
      had finished he said:

“You want your dog? That will cost four francs.” She gave a
      jump. All her grief was at an end at once.

“Do you suppose I am going to bring my ropes, my windlass, and set
      it up, and go down there with my boy and let myself be bitten, perhaps, by
      your cursed dog for the pleasure of giving it back to you? You should not
      have thrown it down there.”

As soon as she entered the house she called Rose and told her of the
      quarryman''s charges. Rose, always resigned, repeated:

“Four francs! That is a good deal of money, madame.” Then she
      added: “If we could throw him something to eat, the poor dog, so he
      will not die of hunger.”

Mme. Lefevre approved of this and was quite delighted. So they set out
      again with a big piece of bread and butter.

They cut it in mouthfuls, which they threw down one after the other,
      speaking by turns to Pierrot. As soon as the dog finished one piece he
      yelped for the next.

One morning as they were just letting fall the first mouthful they
      suddenly heard a tremendous barking in the pit. There were two dogs there.
      Another had been thrown in, a large dog.

“Pierrot!” cried Rose. And Pierrot yelped and yelped. Then
      they began to throw down some food. But each time they noticed distinctly
      a terrible struggle going on, then plaintive cries from Pierrot, who had
      been bitten by his companion, who ate up everything as he was the
      stronger.

And, suffocating at the thought of all the dogs living at her expense, she
      went away, even carrying back what remained of the bread, which she ate as
      she walked along.

It was a wedding procession that was coming along the road between the
      tall trees that bounded the farms and cast their shadow on the road. At
      the head were the bride and groom, then the family, then the invited
      guests, and last of all the poor of the neighborhood. The village urchins
      who hovered about the narrow road like flies ran in and out of the ranks
      or climbed up the trees to see it better.

The bridegroom was a good-looking young fellow, Jean Patu, the richest
      farmer in the neighborhood, but he was above all things, an ardent
      sportsman who seemed to take leave of his senses in order to satisfy that
      passion, and who spent large sums on his dogs, his keepers, his ferrets
      and his guns. The bride, Rosalie Roussel,' WHERE id = '47483ce4-df10-44b3-81b8-ab924b78ab8b';
COMMIT;